### ISSUE TITLE
Posts URLs

### ISSUE THREAD

**Issue by sinaahmadi** [sfreytag/friday-theme#11]
Hi,

Thanks for this great theme.

I was wondering if it is possible to create the URLs for the posts similar to the pages. Currently, the URL of the posts is based on the following patterns:

`root/year/month/day/[title].html`

Is there a way to make it look like the following?

`root/posts/[title].html`

Based on my experience, Google avoids indexing such pages ("Discovered - currently not indexed") due to (apparently) the link structure. 

Besides, I am getting two `//` in the URLs. What can cause such a problem? (as an example, the URL of this post: https://sinaahmadi.github.io//2019/04/16/text-pre-processing-with-bash.html)

Thanks.

**Comment by sfreytag** [comment]
You should be able to use all the Jekyll config to override the config provided in the theme's config.yml... have a read of https://jekyllrb.com/docs/permalinks/ then you could initially just delete the 2nd line of config.yml (ie, remove the config and revert to the default, which is not date-based) or add your own config on this line.

ie, edit this:

`permalink: /:categories/:year/:month/:day/:title.html`

For the second one, what's the value of your `base_url` in the config file? If it is `"/"` then what happens if you set it to just an empty string `""` ?

**Comment by sinaahmadi** [comment]
Thanks very much for your response.
